#NN Settings
hiddenLayers = 21
lookAheadCandles = 10
iterations = 1000
error = 0.03
learnRate = 0.01
momentum = 0.1

#Strat Settings
minPercentIncrease = 3
candlesForShort = 3
candlesForLong = 10

#Indicator Settings
RSI = [14]
SMA = [10, 50]