#NN Settings
hiddenLayers = 3
lookAheadCandles = 6
iterations = 100
error = 0.0001
learnRate = 0.05
momentum = 0.1

#Strat Settings
minPercentIncrease = 2
candlesForShort = [6]
candlesForLong = [6]
stopLoss = 3

#Indicator Settings
RSI = [14]
SMA = [50, 1000]